### ISSUE TITLE
Firmware for new device - SN30Pro+

### ISSUE THREAD

**Issue by cmol** [fwupd/missing-firmware-8bitdo#5]
As requested, an issue for the new device and its firmware:
https://github.com/fwupd/fwupd/issues/1503

A new device is on the market, the SN30Pro+. It has its own firmware and separate versioning from the SN30Pro. Firmware is available on: https://support.8bitdo.com/
Currently in version 3.01.

Please let me know how I can aid in adding this device to fwupd.

Thank you!

**Comment by superm1** [comment]
i'm not sure how closely the 8bitdo people follow this (but the repo is for them to track issues).

The easiest way to help would be to make a PR to this repo: https://github.com/fwupd/8bitdo-firmware

You can test using the snap from the edge channel if you want to test the fwupd changes too.

**Comment by rhansen** [comment]
I think this was fixed by fwupd/8bitdo-firmware#22, however:
  * `fwupdmgr get-devices` doesn't show the controller unless it's in bootloader mode (L+R+Start).
  * `fwupdmgr get-devices` only shows firmware v1.10. I think it's misdetecting the SN30 Pro+ as an M30 when it's in bootloader mode.

**Comment by cmol** [comment]
If the firmware is there, I guess we should close this issue, and take the rest on fwupd/8bitdo-firmware#22
